name: sega_learn
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - colorama=0.4.6
  - contourpy=1.3.1
  - cycler=0.11.0
  - fonttools=4.51.0
  - freetype=2.12.1
  - icc_rt=2022.1.0
  - icu=73.1
  - intel-openmp=2023.1.0
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=17.2
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.2
  - pandas=2.2.3
  - pillow=11.0.0
  - pip=24.2
  - ply=3.11
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.11.11
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - qt-main=5.15.2
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.2
  - tqdm=4.66.5
  - tzdata=2024b
  - unicodedata2=15.1.0
  - vc=14.40
  - vs2015_runtime=14.42.34433
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - black==23.12.1
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - click==8.1.8
      - databind==4.5.2
      - databind-core==4.5.2
      - databind-json==4.5.2
      - deprecated==1.2.15
      - docspec==2.2.1
      - docspec-python==2.2.1
      - docstring-parser==0.11
      - idna==3.10
      - jinja2==3.1.5
      - markupsafe==3.0.2
      - mypy-extensions==1.0.0
      - nr-date==2.1.0
      - nr-stream==1.1.5
      - nr-util==0.8.12
      - pathspec==0.12.1
      - platformdirs==4.3.6
      - pydoc-markdown==4.8.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - tomli==2.2.1
      - tomli-w==1.1.0
      - typeapi==2.2.3
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - watchdog==6.0.0
      - wrapt==1.17.0
      - yapf==0.43.0
